# Generated by Django 3.0.4 on 2020-04-24 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctor',
            name='imageURL',
            field=models.CharField(max_length=600),
        ),
    ]
